# Generated by Django 3.2 on 2023-05-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
